---
# Source: isd-argo-vault/templates/vaultauth.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vaultauth
spec:
  method: kubernetes
  mount: demo-auth-mount
  kubernetes:
    role: argocd-role
    serviceAccount: default
    audiences:
      - vault
---
# Source: isd-argo-vault/templates/static-secrets/carina-manager-static-secret.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: oes-carina-config
  
spec:
  type: kv-v2

  # mount path
  mount: kvv2

  # path of the secret
  path: isdargo/oes-carina-config

  # dest k8s secret
  destination:
    name: oes-carina-config
    create: false

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: vaultauth
---
# Source: isd-argo-vault/templates/static-secrets/gate-static-secret.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: oes-gate-config
  
spec:
  type: kv-v2

  # mount path
  mount: kvv2

  # path of the secret
  path: isdargo/oes-gate-config

  # dest k8s secret
  destination:
    name: oes-gate-config
    create: false

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: vaultauth
---
# Source: isd-argo-vault/templates/static-secrets/oes-audit-client-config-static-secret.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: oes-audit-client-config 
  
spec:
  type: kv-v2

  # mount path
  mount: kvv2

  # path of the secret
  path: isdargo/oes-audit-client-config

  # dest k8s secret
  destination:
    name: oes-audit-client-config
    create: false

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: vaultauth
---
# Source: isd-argo-vault/templates/static-secrets/oes-audit-service-config-static-secret.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: oes-audit-service-config
  
spec:
  type: kv-v2

  # mount path
  mount: kvv2

  # path of the secret
  path: isdargo/oes-audit-service-config

  # dest k8s secret
  destination:
    name: oes-audit-service-config
    create: false

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: vaultauth
---
# Source: isd-argo-vault/templates/static-secrets/oes-autopilot-config-static-secret.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: oes-autopilot-config 
  
spec:
  type: kv-v2

  # mount path
  mount: kvv2

  # path of the secret
  path: isdargo/oes-autopilot-config

  # dest k8s secret
  destination:
    name: oes-autopilot-config
    create: false

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: vaultauth
---
# Source: isd-argo-vault/templates/static-secrets/oes-datascience-config-static-secret.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: oes-datascience-config
  
spec:
  type: kv-v2

  # mount path
  mount: kvv2

  # path of the secret
  path: isdargo/oes-datascience-config

  # dest k8s secret
  destination:
    name: oes-datascience-config
    create: false

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: vaultauth
---
# Source: isd-argo-vault/templates/static-secrets/oes-db-static-secret.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: oes-db
  
spec:
  type: kv-v2

  # mount path
  mount: kvv2

  # path of the secret
  path: isdargo/oes-db

  # dest k8s secret
  destination:
    name: oes-db
    create: true

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: vaultauth
---
# Source: isd-argo-vault/templates/static-secrets/oes-platform-config-static-secret.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: oes-platform-config 
  
spec:
  type: kv-v2

  # mount path
  mount: kvv2

  # path of the secret
  path: isdargo/oes-platform-config

  # dest k8s secret
  destination:
    name: oes-platform-config
    create: false

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: vaultauth
---
# Source: isd-argo-vault/templates/static-secrets/oes-sapor-config-static-secret.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: oes-sapor-config 
  
spec:
  type: kv-v2

  # mount path
  mount: kvv2

  # path of the secret
  path: isdargo/oes-sapor-config

  # dest k8s secret
  destination:
    name: oes-sapor-config
    create: false

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: vaultauth
---
# Source: isd-argo-vault/templates/static-secrets/oes-visibility-config-static-secret.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: oes-visibility-config
  
spec:
  type: kv-v2

  # mount path
  mount: kvv2

  # path of the secret
  path: isdargo/oes-visibility-config

  # dest k8s secret
  destination:
    name: oes-visibility-config
    create: false

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: vaultauth
---
# Source: isd-argo-vault/templates/static-secrets/rabbitmq-static-secret.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: rabbitmq
  
spec:
  type: kv-v2

  # mount path
  mount: kvv2

  # path of the secret
  path: isdargo/rabbitmq

  # dest k8s secret
  destination:
    name: rabbitmq
    create: true

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: vaultauth
---
# Source: isd-argo-vault/templates/static-secrets/redis-static-secret.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: redis 
  
spec:
  type: kv-v2

  # mount path
  mount: kvv2

  # path of the secret
  path: isdargo/redis

  # dest k8s secret
  destination:
    name: releasename-redis    #get this secret from te namespace
    create: false

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: vaultauth
