apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: {{ .Values.vaultauth }}
spec:
  method: kubernetes
  mount: {{ .Values.vaultauthmount }}
  kubernetes:
    role: {{ .Values.vaultrole }}
    serviceAccount: default
    audiences:
      - vault

