apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: oes-audit-service-config
  
spec:
  type: kv-v2

  # mount path
  mount: {{ .Values.vaultmount }}

  # path of the secret
  path: {{ .Values.vaultpath }}/oes-audit-service-config

  # dest k8s secret
  destination:
    name: oes-audit-service-config
    create: false

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: {{ .Values.vaultauth }}
