apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: redis 
  
spec:
  type: kv-v2

  # mount path
  mount: {{ .Values.vaultmount }}

  # path of the secret
  path: {{ .Values.vaultpath }}/redis

  # dest k8s secret
  destination:
    name: releasename-redis    #get this secret from te namespace
    create: false

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: {{ .Values.vaultauth }}
