# Enable Build Analysis
APP:
   ENVIRONMENT: dev
   DEBUG: True
   # Only accept True or False
   BIND: 0.0.0.0:5005
   WORKERS: 1
   PROTOCOL: http://
   TIMEOUT: 3600
   CELERY_ENABLED: True
   # Only accept True or False

OBJECT_STORAGE:
      ENDPOINT: http://isd-tcb-minio:9000
      BUCKET_NAME: autopilot
POSTGRES:
      USERNAME: 'postgres'
      PASSWORD: 'POSTGRES-PASSWORD'
      HOST: oes-db
      PORT: 5432
      DB: autopilotqueue

RABBITMQ:
      USERNAME: 'rabbitmq'
      PASSWORD: 'RABBITMQ-PASSWORD'
      HOST: rabbitmq-service
      PORT: 5672
