spring:
  datasource:
    url: jdbc:postgresql://oes-db:5432/oesdb
    username: 'postgres'
    password: 'POSTGRES-PASSWORD'

message-broker:
  enabled: true
  username: 'rabbitmq'
  password: 'RABBITMQ-PASSWORD'
  host: rabbitmq-service
  port: 5672
  endpoint:
    name: rabbitmq

standardErrorCodes:
  filePath: /opsmx/conf/standard-error-code.csv

argo:
  manifest:
    newArgoAgentTemplate: newargoagentmanifest.template
    newArgoAgentWithoutUrlTemplate: newargoagentmanifestwithouturl.template
    existingArgoAgentTemplate: existingargoagentmanifest.template
    existingArgoAgentWithoutUrlTemplate: existingargoagentmanifestwithouturl.template
    newArgoAgentWithoutRolloutsTemplate: newargoagentwithoutrollouts.template
    newArgoAgentWithoutRolloutsWithoutUrlTemplate: newargoagentwithoutrolloutswithouturl.template

secretManagement:
  source:
    config: db
  encryption: true
oes:
  rbac:
    enabled: true
  admin:
    user: admin
  platform:
    url: http://oes-platform:8095
  visibility:
    url: http://oes-visibility:8096
  auditservice:
    enabled: true
    url: "http://oes-audit-service:8097"
  dashboard:
    url: http://oes-dashboard:8094
  commongateurl: https://only-isd.hyd-dev.opsmx.net/gate
spinnaker:
  encrypt:
    enabled: false
  sync:
    permission:
      enabled: true

datasources:
  platform: true

pipeline-promotion:
  github:

    enabled: true

    username:  git/stash_username
    token: git/stash_token
    branch: master
    cloneUrl: https://git/stash_username:git/stash_token@github.com/OpsMx/standard-gitops-repo
  bitbucket:

    enabled: false

    username:  git/stash_username
    token: git/stash_token
    branch: master
    cloneUrl: https://git/stash_username:git/stash_token@github.com/OpsMx//standard-gitops-repo
  amazonS3:

    enabled: false

    accessKeyId: AWS_ACCESS_KEY_ID
    secretAccessKey: AWS_SECRET_ACCESS_KEY
    region: regionofbucket
    bucketName: bucket name.e.g-testbucket

## Set the below field to true if agent for kubernetes
kubernetes:
  kinds:
  omitKinds:
  - podPreset
  agent:
    enabled: true
    serverInternalHostName: opsmx-controller-controller1
    serverPort: 9003
    caCertfile: /opt/opsmx/controller/ca.crt
    certFile: /opt/opsmx/controller/cert/tls.crt
    keyFile: /opt/opsmx/controller/cert/tls.key
    image: quay.io/opsmxpublic/agent-client:v4.2.3
  template:
    path: /opt/opsmx/controller
    kubectlTemplateFileName: kubeconfig.template
    manifestTemplateFileName: deploy-agent.template
