spring:
  datasource:
    url: jdbc:postgresql://oes-db:5432/auditdb
    username: 'postgres'
    password: 'POSTGRES-PASSWORD'
logging:
  level:
    com.opsmx.auditclientservice: INFO
standardErrorCodes:
  filePath: /opsmx/conf/standard-error-code.csv
oes:
  admin:
    user: admin
feign:
  client:
    platformservice:
      name: platformservice
      url: http://oes-platform:8095
    visibilityservice:
      name: visibilityservice
      url: http://oes-visibility:8096

insights:
  scheduler:
    enable: false
    fixedDelay:
      in:
        milliseconds: 120000
    initialDelay:
      in:
        milliseconds: 300000
scheduler:
  threads: 16
