
spring:
  datasource:
    url: jdbc:postgresql://oes-db:5432/platformdb
    username: 'postgres'
    password: 'POSTGRES-PASSWORD'
ldap.managerPassword: 'opsmxadmin123'
redis:
    connection: redis://:REDIS-PASSWORD@isd-tcb-redis-master:6379
#datasource.url: jdbc:postgresql://oes-db:5432/visibilitydb
#postgres.password: 'networks123'
#postgres.username: 'postgres'

datasource:
  secretManagement:
    source: db
rbacEnabled: true
supportedFeatures:
  - deployment_verification
  - sapor
  - visibility
userGroup:
  superAdminGroups: admin
fixedDelay:
  in:
    milliseconds: 120000
initialDelay:
  in:
    milliseconds: 300000
scheduler:
  workerThreads: 50
user:
  source: ldap
ldap:
  enabled: true
  url: ldap://openldap:389
  managerDn: cn=admin,dc=example,dc=org
  groupSearchBase: ou=groups,dc=example,dc=org
  groupSearchFilter: member={0}
  groupRoleAttributes: cn
  userDnPattern: cn={0},dc=example,dc=org

oes:
  sapor:
    url: http://oes-sapor:8085
  autopilot:
    url: http://oes-autopilot:8090
  dashboard:
    url: http://oes-dashboard:8094
  visibility:
    url: http://oes-visibility:8096
  auditclient:
    url: http://oes-audit-client:8098
  policyGate:
    url: "https://only-isd.hyd-dev.opsmx.net/gate"
    path: /v1/data/
  ui:
  # Ex: "https://oes-poc.dev.opsmx.org/"
    url: "https://only-isd.hyd-dev.opsmx.net/ui"
  gate:
    url: http://oes-gate:8084
  carinamanager:
    url: "http://oes-carina"
    managerport: 8091
    rbacport: 8092
  approvalGate:
    apiUrl: https://only-isd.hyd-dev.opsmx.net/gate/visibilityservice/v5/approvalGates/{id}/trigger

  verificationGate:
    apiUrl: https://only-isd.hyd-dev.opsmx.net/gate/autopilot/api/v3/registerCanary

logging:
  level:
    com.opsmx.platformservice: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO

standardErrorCodes:
  filePath: /opsmx/conf/standard-error-code.csv
argoRollout:
  appAutoCreation: false
